version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./emenu/.env
  redis:
    image: redis:6-alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A emenu worker -l INFO
    volumes:
      - .:/app
    env_file:
      - ./emenu/.env
    depends_on:
      - app
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A emenu beat -l INFO
    volumes:
      - .:/app
    env_file:
      - ./emenu/.env
    depends_on:
      - app