version: "3.9"

services:
  app:
    build:
      context: .
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./emenu/.env
  redis:
    image: redis:6-alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - .:/code
    env_file:
      - ./emenu/.env
    depends_on:
      - db
      - redis
      - app